### ISSUE TITLE
API 设计

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-cascade-multi-select#1]
尽量与 [uxcore-cascade-select](https://github.com/uxcore/uxcore-cascade-select)  的 prop保持一致，可以对应地新增 prop 完成更丰富的功能。 新增的 prop 回复在下面。

**Comment by guyunxiang** [comment]
## API

## Props

| 选项 | 描述 | 类型 | 必填 | 默认值 |
|---|---|---|---|---|
| prefixCls | 默认的类名前缀 | String | `false`| "kuma-multi-cascader" |
| className | 自定义类名 | String | `false` | "" |
| options | 横向级联的数据 | Array | `false` | [] |
| value | 可由外部控制的值 | Array | `false` | null |
| defaultValue | 初始默认的值 | Array | `false` | [] |
| cascadeSize | 级联层级数 | number | `false` | 3 | 
| noDataContent（新增） | 没有子项级联数据时显示内容 | String | `false` | 'No Data' 或 '没有数据' |
| allowClear | 是否允许清空 | bool | `false` | true | |
| readOnly（新增） | 只读模式，可以查看所有选项，不可修改选中或清空 | bool | `false` | false |
| locale（新增） | 'zh-cn' or 'en-us' | String | `false` | 'zh-cn' |
| onSelect（新增） | 选中选项的回调函数 | function | `false` | (res) => {} |

### Props.options

** 示例 **
```javascript
const options = [{
  value: 'zhejiang',
  label: '浙江',
  children: [{
    value: 'hangzhou',
    label: '杭州',
    children: [{
      value: 'xihu',
      label: '西湖',
    }],
  }],
}, {
  value: 'jiangsu',
  label: '江苏',
  children: [{
    value: 'nanjing',
    label: '南京',
    children: [{
      value: 'zhonghuamen',
      label: '中华门',
    }],
  }],
}];
```

这次交互的设计是只设计了选择面板的内容，没有包含input的输入框的部分，原有的Props.placeholder暂不设计
onSelect返回值：二级，三级全部选中，则返回父级（一级）的key，半选中的父级，则返回子集的key。与原横向级联多选组件返回值逻辑一致。

**Comment by eternalsky** [comment]
noDataContent 这个和 Select 一致改成 noDataContent 吧~ @guyunxiang32
