### ISSUE TITLE
打开面板，直接点击确定，值被清空

### ISSUE THREAD

**Issue by 2999** [uxcore/uxcore-cascade-multi-select#13]
经过测试，这个问题更详细的描述应该是：

以props.value的方式传入值，如果打开面板后不进行手动选择，而是直接点击“确定”按钮，onOk得到的值，还是上次手动操作时选中的值；
如果之前未进行过手动选择，则返回空值。

![111](https://cloud.githubusercontent.com/assets/1653891/26022285/ba514b32-37d3-11e7-8b8b-11a63f335cbc.gif)

**Comment by lpgray** [comment]
@2999 OK，我看一下

**Comment by lpgray** [comment]
@2999 看看好了没
```
npm install uxcore-casace-multi-select@latest
```
