### ISSUE TITLE
点击清空时，对于一些 ”已勾选，且disabled“状态的选项，应该不清空

### ISSUE THREAD

**Issue by KevLeong** [uxcore/uxcore-cascade-multi-select#14]
![default](https://user-images.githubusercontent.com/26003213/33641428-16fcab00-d9fb-11e7-8152-bb201ab0911f.png)

如图，现在是点击清空时，会把所有的选项都清空。是否可以增加一个props，使其不清空该类型

**Comment by lpgray** [comment]
@mosikoo please fix this bug

**Comment by lpgray** [comment]
Solved at 0.7.0
