### ISSUE TITLE
组件开发

### ISSUE THREAD

**Issue by guyunxiang** [uxcore/uxcore-cascade-multi-select#2]
目前组件开发基本完成，当时和交互讨论是只做横向级联选择的面板部分（多级选择列表+结果列），不包含input选择框部分。
原来的横向级联选择组件是包含了一个input，点击input展示横向级联。
是否需要再封装一个带input的组件？需不需要封装成FormField？

**Comment by eternalsky** [comment]
这个组件里应该包括 input，只是面板可以抽离出来使用。这个 prj 不需要封装 FormFIeld，FormField 单独做一个 prj，不在这次组件范围里。
