### ISSUE TITLE
cascade-multi-select 是否考虑增加些字段来满足个性化需求

### ISSUE THREAD

**Issue by panwenhua** [uxcore/uxcore-cascade-multi-select#22]
1   .kuma-cascade-multi-list-item 上的  title  可以加一个字段来控制是否显示 title
原因：选项不一定都是字符串，有可能是jsx  比如   <div style={{color:'red'}}>北京市</div>
这个时候鼠标移上去就会显示 [object Object]。
2. 可以添加一个字段用来展开指定节点。
原因： 自己添加了节点搜索功能，发现无法展开指定的节点

**Comment by lpgray** [comment]
uxcore-cascade-select@0.7.3 等 @eternalsky 发大包 uxcore 吧

**Comment by eternalsky** [comment]
ok，明天会发大包。
